In [1]:
import torch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [1]:
import torch

In [2]:
# torch.empty(size): uninitiallized
x = torch.empty(1) # scalar
print(x)

tensor([0.])


In [3]:
x = torch.empty(3) # scalar
print(x)

tensor([0., 0., 0.])


In [4]:
x = torch.empty(2,3) # 2D
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [8]:
x = torch.empty(2,2,3) # 3D
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [11]:
# torch.rand(size): random numbers [0, 1]

x = torch.rand(5, 3)
print(x)

tensor([[0.0778, 0.1212, 0.9690],
        [0.2972, 0.6186, 0.3407],
        [0.7264, 0.9558, 0.9703],
        [0.6273, 0.3584, 0.4453],
        [0.1059, 0.3344, 0.3628]])


In [12]:
# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x = torch.zeros(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# construct from data

x = torch.tensor([5.5, 3])
print(x.size())

torch.Size([2])


In [41]:
x = torch.tensor([5.5, 3], requires_grad=True)
x

tensor([5.5000, 3.0000], requires_grad=True)

In [42]:
# Operations
y = torch.rand(2, 2)
x = torch.rand(2, 2)

In [50]:
x

tensor([[0.8159, 0.0922],
        [0.8858, 0.8232]])

In [51]:
y

tensor([[0.6248, 0.0082],
        [0.7042, 0.4704]])

In [52]:
z = x + y
z

tensor([[1.4406, 0.1004],
        [1.5900, 1.2936]])

In [53]:
z = y + x
z

tensor([[1.4406, 0.1004],
        [1.5900, 1.2936]])

In [54]:
# same things
torch.add(x,y)

tensor([[1.4406, 0.1004],
        [1.5900, 1.2936]])

In [57]:
# same as z and torch.add(x,y)

x.add_(y)

tensor([[3.5060, 0.2089],
        [3.8843, 3.0576]])

In [59]:
z = x - y
z = torch.sub(x, y)
z

tensor([[1.4406, 0.1004],
        [1.5900, 1.2936]])

In [60]:
z = x * y
z = torch.mul(x,y)
z

tensor([[7.2414, 0.0227],
        [8.9115, 5.3938]])

In [61]:
z = x / y
z = torch.div(x,y)
z

tensor([[1.6975, 1.9246],
        [1.6931, 1.7333]])

# Slicing

In [63]:
x = torch.rand(5,3)
print(x)

print(x[:, 0]) # all rows, column 0

print(x[1, :]) # row 1, all columns

print(x[1,1]) # element at 1, 1

tensor([[0.0474, 0.7953, 0.0061],
        [0.8292, 0.7278, 0.5395],
        [0.2520, 0.7213, 0.6804],
        [0.1444, 0.4901, 0.1305],
        [0.7937, 0.9423, 0.3120]])
tensor([0.0474, 0.8292, 0.2520, 0.1444, 0.7937])
tensor([0.8292, 0.7278, 0.5395])
tensor(0.7278)


In [64]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.7278397083282471


# Reshape with torch.view()

In [65]:
x = torch.randn(4, 4)
x

tensor([[-1.5325, -1.0445, -0.3341, -0.9523],
        [ 0.9449, -2.0380, -2.1086, -0.6136],
        [ 0.4495, -0.4670,  2.2920, -0.5925],
        [-1.0601, -0.4501, -0.6894, -0.2021]])

In [66]:
y = x.view(16) # (4*4=16)
y 

tensor([-1.5325, -1.0445, -0.3341, -0.9523,  0.9449, -2.0380, -2.1086, -0.6136,
         0.4495, -0.4670,  2.2920, -0.5925, -1.0601, -0.4501, -0.6894, -0.2021])

In [69]:
# the size -1 is inferred from other dimensions

z = x.view(-1, 8)  
z

tensor([[-1.5325, -1.0445, -0.3341, -0.9523,  0.9449, -2.0380, -2.1086, -0.6136],
        [ 0.4495, -0.4670,  2.2920, -0.5925, -1.0601, -0.4501, -0.6894, -0.2021]])

In [70]:
print(z.size())

torch.Size([2, 8])


In [71]:
# if -1 it pytorch will automatically determine the necessary size

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# Numpy to Torch

In [77]:
# Converting a Torch Tensor to a NumPy array and vice versa is very easy

import numpy as np

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [78]:
b = a.numpy()

print(b)

print(type(b))

[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [79]:
# Carful: If the Tensor is on the CPU (not the GPU),
# both objects will share the same memory location, so changing one
# will also change the other

a.add_(1) # a+1 = [ [1. 1. 1. 1. 1.]+ [1. 1. 1. 1. 1.]]

print(a)

tensor([2., 2., 2., 2., 2.])


In [80]:
print(b)

[2. 2. 2. 2. 2.]


# numpy to torch with .from_numpy(x)

In [82]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)

print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [83]:
# again be careful when modifying
a += 1

print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [85]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    # z = z.numpy() # not possible because numpy cannot handle GPU tenors
    # move to CPU again
    z.to("cpu")       # ``.to`` can also change dtype together!
    # z = z.numpy()

In [86]:
x = torch.ones(5, requires_grad =True)
print(x)

tensor([1., 1., 1., 1., 1.], requires_grad=True)


# Gradient Calculation With Autograd